apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    reloader.stakater.com/match: "true"
  name: application-mockup-configuration-configmap-env
data:
  REGION: us-east-1
  ECR_REPOSITORY: public.ecr.aws/p1c6t8w0/public_mockup
  SECRET_NAME: regcred
  NAMESPACE_NAME: {{ .Release.Namespace }}
  DOCKER_SECRET_NAME: regcred
