apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mockup.fullname" . }}
  labels:
    {{- include "mockup.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mockup.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mockup.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mockup.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          envFrom:
          - secretRef:
              name: mockup-secret-env
          - configMapRef:
              name: application-mockup-configuration-configmap-env
#          env:
#            - name: CONFIG_LOCATION
#              value: "/home/config/application-mockup-configuration.yml"
          volumeMounts:
            - name: application-mockup-configuration
              mountPath: /home/config/application-mockup-configuration.yml
              subPath: application-mockup-configuration.yml
            - name: vault-second-configuration
              mountPath: /storage/vault-configuration.yml
              subPath: vault-configuration.yml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: application-mockup-configuration
          configMap:
            name: application-mockup-configuration
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
