kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-role-binding
subjects:
- kind: ServiceAccount
  name: sa-secret
  namespace: {{ .Release.Namespace }}
  apiGroup: ""
roleRef:
  kind: Role
  name: role-full-access-to-secrets
  apiGroup: ""