init:
  message: "Test message loaded from default application.yml file"

spring:
  application:
    name: mockup
  cloud:
    kubernetes:
      discovery-server-url: "http://spring-cloud-kubernetes-discoveryserver"

server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
