init:
  message: "Test message loaded from default application.yml file"

spring:
  application:
    name: mockup
  cloud:
    kubernetes:
      discovery:
        discovery-server-url: "spring-cloud-kubernetes-discoveryserver.default.svc:8761"
        all-namespaces: true

server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
