spring:
  application:
    name: int-test-project
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
  jackson:
    time-zone: UTC

init:
  message: "Test message loaded from default application.yml file"

server:
  port: 8761
#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
